---
- name: Reset antigen cache
  ansible.builtin.command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  ansible.builtin.command: "timeout 30s /bin/zsh -c 'source {{ zsh_config }}; antigen update'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

- name: Create cache dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
  become: true
  with_items:
    - "{{ zsh_antigen_path }}/bundles/robbyrussell/oh-my-zsh/cache/completions"
