---
scenario:
  name: shared
driver:
  name: docker
platforms:
  - name: ansible-role-zsh-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_shared: yes
        zsh_theme: powerlevel10k
