---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Apt-proxy
      ansible.builtin.copy:
        content: "Acquire::http::Proxy \"{{ lookup('env', 'APT_PROXY') }}\"; Acquire::https::Proxy \"false\";"
        dest: /etc/apt/apt.conf.d/01proxy
        mode: "0644"
      failed_when: false

    - name: Create testuser
      ansible.builtin.user:
        name: testuser
        home: /home/testuser
        shell: /bin/bash
